language:
- scala
sudo: required
dist: trusty
jdk:
- oraclejdk8
scala:
- 2.12.7
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
  - $HOME/.ivy2
git:
  depth: 1
script:
- echo "TRAVIS_PULL_REQUEST" $TRAVIS_PULL_REQUEST
- echo "TRAVIS_BRANCH" $TRAVIS_BRANCH
- echo "TRAVIS_TAG" $TRAVIS_TAG
- echo "repo" $TRAVIS_REPO_SLUG
- set -o pipefail; set -e; skipLogs="Resolving |Compiling |Done updating|Updating |scoverage|coverage-report";
  if [[ $TRAVIS_PULL_REQUEST != "false" || $TRAVIS_REPO_SLUG != "gearpump/gearpump" ]]; then 
    sbt -jvm-opts project/travis/jvmopts clean +assembly scalastyle test:scalastyle unidoc coverage test | grep -v -E "$skipLogs";
    sbt coverageReport;
  elif [[ $TRAVIS_BRANCH == "master" ]]; then
    sbt -jvm-opts project/travis/jvmopts clean +assembly +publish | grep -v -E "$skipLogs";
    sbt -jvm-opts project/travis/jvmopts scalastyle test:scalastyle unidoc coverage test  | grep -v -E "$skipLogs";
    sbt coverageReport;
  elif [[ $TRAVIS_TAG != "" ]]; then
    sbt -jvm-opts project/travis/jvmopts clean +assembly +packArchiveZip | grep -v -E "$skipLogs";
  fi
after_success:
- if [[ $TRAVIS_PULL_REQUEST != "false" || $TRAVIS_REPO_SLUG != "gearpump/gearpump" || $TRAVIS_BRANCH == "master" ]]; then
    bash <(curl -s https://codecov.io/bash);  
  elif [[ $TRAVIS_TAG != "" ]]; then
    set -o pipefail;
    openssl aes-256-cbc -K $encrypted_3d8d53d5fdbf_key -iv $encrypted_3d8d53d5fdbf_iv -in secring.asc.enc -out secring.asc -d;
    sbt +publishSigned sonatypeReleaseAll | grep -v -E "Resolving ";
  fi 
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IlnJDspR7s2Pj9pViL250ijL2AK3YUU/e1EIaGPqN0NFQynuWYrr2LlIXA5PQ7PvwRepDT0OfS979xWi1Hx0Eg+aMT1wArtAjU/FqDiYE4H2U0RW7fVV5Zq9EtJ3tqKLEdum5aveg1h2PqwAMXgp1JO+UW7CwEEmp6C8MFZhFTSb6yWc87gfP+jHQhxMwQp+yH9g/AdccoU++07fG0sIZnb/rjCKDa81kCHiQvrKrdObkDGEGcB3bVSWL7DrQvyfDb4vuJBa3pgHx8U3PkT1Ld58CRFKrlGVsoUYdYHzB2vDkzJaGR1a+t/s8sR45JLpEac4XyGyfkJEmmtF1bQ9o/AbYgTfVuMKEcQNVq8w6INV+7B2ol5ie9Kk1hZvbBVFyThT5hzYPMGO6Hx963kvqRPXqZFcadEu8mNIeL0c8Mb2z2qFFB3FO6n1MQrlQ/3PjheWbfqjb9ut54B+7ToMdTkXeH7RgXHIVv47iZlTHemUPQhjyMaoNBlpLapG21wYSi8JbqQgiq2atObNWt25cqRiA8k3p0RD6I6vRWHcWRGn7DdfR8tg4GhJEKShj7cvTTMTa6xoEW6LTYx/jkJ5eHvmqhCZQ8D3nNnZeP71NdQWcOCmofp2K+at3YctQQ7xQGU9kkYXpv6gAUTPcmz+rFwHokTzaA28aBnLaMa/HLc=
  file_glob: true
  file: output/target/gearpump-*.zip  
  on:
    repo: xunchangguo/gearpump
    tags: true
    all_branches: true
